version: '3.4'

services:
  craps-simulator-service-compose:
    image: ${DOCKER_REGISTRY-}craps-simulator-service
    build:
      context: .
      dockerfile: craps-simulator.service/Dockerfile
  craps-simulator-react-compose:
    image: ${DOCKER_REGISTRY-}craps-simulator-react
    build:
      context: .
      dockerfile: craps-simulator.react/Dockerfile
